### ISSUE TITLE
Trajectories generated dosent have joint velocities and joint acceleration 

### ISSUE THREAD

**Issue by lakshmip001** [ros-industrial-consortium/trajopt_ros#65]
I created a trajectory and published to the joint_trajectory_action but the joint velocities and constraints are not available in the trajectory so my robot is not moving this the trajectory message being published.

```yaml
positions: [-1.5295043600590792, -0.4678241770981601, -2.798475681586013, 1.6710705972247073, -1.5971836662472205, -1.53520336321362]
        velocities: []
        accelerations: []
        effort: []
        time_from_start: 
          secs: 4
          nsecs: 750000000
```

Kindly please let me know how I can solve this problem(add joint velocities in the trajectory)
